import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Clean Up",
	description:
		"Generated by create next app and cleaned the rubbish created by next",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
